Dockerfile
This PRs add a build step that installs AWS IAM Authenticator directly [from the source](https://amazon-eks.s3-us-west-2.amazonaws.com/1.10.3/2018-07-26/bin/linux/amd64/aws-iam-authenticator). Before creating the this PR, i made a very simple test using one of our projects:
Everything works great. 🙃
=> Add AWS IAM Authenticator Installation step

entrypoint.sh
Add the ability for the `pulumi/actions` container to add the Pulumi command-line output  as comments on pull requests. (As suggested by @najohnson.)
I've set it up so that we _don't_ leave comment on PRs by default. To get this behavior you need to set to set the `COMMENT_ON_PR` environment variable, as well as make sure `GITHUB_TOKEN` is available to the GitHub workflow action.
Here's a sample `main.workflow`, using the `dev` tag of the container.
```
action "Pulumi Preview chrsmith/github-actions-resources" {
uses = "docker://pulumi/actions:dev-chris"
args = ["preview"]
env = {
PULUMI_CI = "pr"
COMMENT_ON_PR = "1"
}
secrets = [
"PULUMI_ACCESS_TOKEN",
"GITHUB_TOKEN",
]
}
```
The reason we don't want to enable this by default, is that if you are using the [Pulumi GitHub …
=> Add option for commenting on Pull Requests

action.yaml, package.json, src/config.ts, src/main.ts, yarn.lock
This adds configuration to our action step.
There's one small catch, we are evaluating the input variables multiple times. In `action.yml` and on every input which is required we validate as well, the problem is that we don't get types based on either of these validations and generally I don't like typecasting.
`runtypes` offers more than what the Github Actions configuration does as well.
fixes #45
=> feat: Add configuration

src/libs/exec.ts, src/libs/pulumi-cli.ts, src/libs/utils.ts, src/main.ts
Adds a check to see if Pulumi CLI is available.
**Note**: The implementation is heavily inspired by [docker/build-push-action](https://github.com/docker/build-push-action).
=> feat: Check if Pulumi CLI is available

action.yaml, src/config.ts
This configuration is used to define where the Pulumi code is located. We probably need this argument to ensure we are updating the correct Pulumi code, and AFAIK there is no other way to define this.
Maybe we want `working-directory` as is defined in [Workflow Syntax](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions) for the run command?
I went for `cwd` since that is _not_ `working-directory`, so that people don't miss where to put the input variable :)
=> feat: Add cwd to inputs

action.yml
Fixes issue causing this error:
```shell
Warning: Unexpected input(s) 'cloud-url', valid inputs are ['command', 'stack-name', 'work-dir', 'comment-on-pr', 'github-token']
```
=> fix: add missing `cloud-url`

.github/workflows/tag.yaml
This pull request adds a Github Workflow that runs on every release and pushes to a `v<major tag>` tag.
E.g.
`1.0.0` --> `v1`
`v1.0.0` --> `v1`
`v2.1.4` --> `v2`
....
**PS**: I have explicitly removed the `latest` tag to discourage users from blindly using `latest` and getting problems :-)
See live demo:
https://github.com/cobraz/workflow-testing/runs/1954713139
=> feat: Add auto major-tagger workflow

dist/index.js, src/__tests__/config.test.ts, src/config.ts, src/main.ts
Creates stacks if they don't exists when `upsert` is set to `true`.
fixes #90
fixes #9
=> feat: Add `upsert` option

.github/husky/pre-commit, .github/workflows/pull_request.yml, .github/workflows/smoke_test_cli_version.yml, .github/workflows/test.yml, .github/workflows/update_dist.yml, .github/workflows/workflow_dotnet_application.yml, .github/workflows/workflow_go_application.yml, .github/workflows/workflow_nodejs_application.yml, .github/workflows/workflow_python_application.yml, package.json
fixes #113
The @pulumi-bot comment below is just an example of what would happen if a user creates a pull request where files in `dist/` are changed. Would love some opinions on whether we want that comment and what we should write :)
/cc @infin8x @stack72
=> ci: Automatically update dist files on every push

.github/workflows/workflow_dotnet_application.yml, .github/workflows/workflow_go_application.yml, .github/workflows/workflow_nodejs_application.yml, .github/workflows/workflow_options.yml, .github/workflows/workflow_python_application.yml
We're hitting the maximum running jobs (60) on GHA all the time, which is fine. The issue is that if we notice something wrong with one workflow (e.g. `up`), we shouldn't need to wait until everyone is completed.
=> ci: enable `fail-fast` on `matrix`

.github/workflows/test.yml, .github/workflows/workflow_options.yml, CHANGELOG.md, README.md, action.yml, src/config.ts, src/main.ts
=> feat: Refresh

src/libs/libs/get-version.ts
Adds a `date` property for the ISO date string returned by the GitHub API that corresponds with a given release. See https://github.com/pulumi/docs/pull/6036 for additional context.
=> Add date to the version record

src/libs/pulumi-cli.ts
We should probably print which version that is running, so it's easier to debug.
=> feat: print matched version

CHANGELOG.md, src/libs/pr.ts
Instead of printing the whole comment "raw", print it collapsed so it doesn't take a lot of space on screen!
=> Print collapsible comments on PRs

src/libs/pr.ts
There has to be a line break after the `summary` block so that the
backticks work as intended.
We have found this issue while trying to latest version from master.
Check the screen shot below.
Edit: 
I noticed that the pipeline failed because it's requesting for the changelog to be updated. Does it need to be as there was no release of this feature yet?
=> Fix collapsible comment

CHANGELOG.md, src/libs/pr.ts
This is a fix for #633.
The problem appears to be from the usage of dedent, which produces mixed indentation levels between `heading` and `body`. On current master, one ends up with a `heading` that looks like this:
```
<details>
<summary>Click to expand Pulumi report</summary>
```
and a `body` that looks like this (note the extra indentation):
```
<details>
<summary>Click to expand Pulumi report</summary>
```
I considered amending the indentation of the `body` string (basically, removing it all), but that would require some unusual formatting that would break the flow of the code, and seems brittle. This change should be a little more robust.
Ideally there would be unit test coverage for this case, but I didn't have time to add it.
=> fix: update PR comment

.github/workflows/workflow.yml
Workflow builds aren't triggered due to our change detector step only checking `dist` folder. We should also run builds when workflows are updated, this addresses that.
=> chore: add workflows to change trigger

CHANGELOG.md, README.md, action.yml, src/__tests__/config.test.ts, src/config.ts
Adds support for configuring colorized output.
I am unsure what exactly is required for contributing to this repo. Please let me know if something more is needed.
Fixes #84
=> feat: Support colorized output

.github/workflows/test.yml
If the random string generated contains valid bash syntax for command substitutions, this script as-is could throw an error if the substitution itself is invalid. See https://github.com/pulumi/actions/runs/7292938581?check_suite_focus=true for an example. Instead, the Bash string should use single quotes to prevent globbing, splitting, and substitutions.
=> Prevent Command Substitution in bash step

CONTRIBUTING.md
This PR clarifies that we prefer each PR to contain no more than one new feature. It also adds copy from pu/pu CONTRIBUTING.md to link community members to issues.
=> Clarify one-feature-per-pr in CONTRIBUTING.md

README.md
This PR documents our intention to support our enterprise customers. As part of a "Pulumi EOL" issue, I did some reading to determine what kind of policies we can publish around version support -- in the case of this repo, only Node support is required to disclose, since yarn, typescript, etc are all build-time dependencies.
It also provides a public announcement of our intention to end support for Node 12 in December.
Closes https://github.com/pulumi/actions/issues/707
=> Document sunsetting policy for Node 12

README.md
This PR documents the `policy-pack` and `policy-pack-config` features. These features have been supported, but slipped through our process to ensure they are documented in the README.
=> README: Alphabetize extra options, add policy pack descriptions

CHANGELOG.md, README.md, src/libs/__tests__/pr.test.ts, src/main.ts
Allow `comment-on-pr-number` to be used to comment on a PR, even when not called from a `pull_request` event.
Fixes #802
=> allow PR comment from non-PR events using `comment-on-pr-number`

CHANGELOG.md, src/libs/pulumi-cli.ts
Windows wasn't using the pulumi bin that get-version resolved to, so with just the new error check would fail all runs. So this also fixes the windows install so it actually uses the pulumi downloaded rather than the default pulumi installed on GHA runners.
=> Check the pulumi installed is what get-version resolved to

.github/workflows/workflow.yml
If the tests use the pulumi installed on the GitHub workers,
then they can potentially mask bugs in the action's install step,
which is what happened in #834.
=> ci/test: Don't use pre-installed Pulumi

src/libs/libs/get-version.ts
This PR differentiates error logs between two different failure modes. It adds a little more context to debug messages when we hit these error conditions. This is in service of https://github.com/pulumi/actions/issues/886 which hits an error case without a lot of debug information available.
=> Differentiate error messages for Semver calculation.

CHANGELOG.md
This PR prepares for the release of the GHA. The only change is an improvement to debug messaging, so this will be a patch release.
=> Prepare changelog for v4.1.1

CHANGELOG.md, src/config.ts
Reverts validation on config map.
=> fix: remove config-map parser

CHANGELOG.md, README.md, action.yml, package.json, src/__tests__/config.test.ts, src/config.ts, yarn.lock
Support passing the `--exclude-protected` flag to `pulumi destroy`. Requires the latest version of `@pulumi/pulumi` where the option is now available in Automation API (see https://github.com/pulumi/pulumi/pull/12734).
Fixes #628
=> feat: Support `exclude-protected` on `destroy`

.github/workflows/workflow.yml, CHANGELOG.md, src/libs/pulumi-cli.ts
Sometimes a release of the CLI contains a bug that is bad enough that we'd prefer users avoid using that version, to avoid the issue. For example, a bug that could cause stack corruption. We'd like to have a holistic way to "taint" a bad release, but in the meantime, one tactical change is to have the action prefer downloading a more recent version of the CLI if the version that is preinstalled has known issues. For now, the list is hardcoded, but in the future it could be stored in a centralized location that the action could check.
Fixes #955
=> feat: Download CLI if preinstalled version is known bad

.github/workflows/workflow.yml
Resolve #989 
Update `.github/workflows/workflow.yml` to use environment file instead of deprecated `set-output` command. 
For more information, see: [https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/)
I found the workflow file that use `set-output` command through the following command:
```bash
$ find . -name '*.yml' -o -name '*.yaml' | xargs egrep '\bset-output\b'
```
**AS-IS**
```yaml
echo "::set-output name=dir::$(npm config get cache)"
```
**TO-BE**
```yaml
echo "dir=$(npm config get cache)" >> $GITHUB_OUTPUT
```
=> chore: Replace deprecated command with environment file

.github/workflows/workflow.yml
https://github.com/pulumi/actions/pull/990#pullrequestreview-1535187586
Use `cache` option in `setup-node` action.
**AS-IS**
```yaml
- name: Get npm cache directory
id: npm-cache-dir
run: |
echo "dir=$(npm config get cache)" >> $GITHUB_OUTPUT
- uses: actions/cache@v3
id: npm-cache
with:
path: ${{ steps.npm-cache-dir.outputs.dir }}
key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
restore-keys: |
${{ runner.os }}-node-
- uses: actions/setup-node@v3
with:
node-version: 16.x
```
**TO-BE**
```yaml
- uses: actions/setup-node@v3
with:
node-version: 16.x
cache: npm
```
=> chore: Use `cache` option in `setup-node` action

.github/workflows/test.yml, .github/workflows/workflow.yml, CHANGELOG.md, README.md, action.yml, src/__tests__/config.test.ts, src/config.ts
Related to / resolves #991
This commit does the following:
- Updates `src/config.ts` to expose the `plan` option
- Updates the `README.md` to reflect that this option is now available.
- Adds a new test that will do a `preview`, save the plan, and then attempt to `up` using the plan.
- Update `action.yml` to reflect this new option
- `.github/workflows/workflow.yml`:
- Adds new steps to each job for generating an Update Plan and ensuring that the file has content when testing `preview`
=> feat: Add Update Plan Functionality

CHANGELOG.md, action.yml
Hi, 
Node 16 reached the [end of life on Sep, 11 2023](https://nodejs.org/en/blog/announcements/nodejs16-eol). 
Node 20 is supported on GitHub Runners since https://github.com/actions/runner/releases/tag/v2.308.0.
This PR updates the runtime
=> chore: node 20 as default runtime

examples/nodejs-azure.yaml, examples/nodejs-google-workload-identity-federation.yaml, examples/nodejs-google.yaml, examples/nodejs-local.yaml, examples/nodejs-pulumi.yaml
This just updates the examples to use the correct GitHub action for setting up node. The repository is https://github.com/actions/setup-node and thus with `actions/setup-nodejs` you will receive the error `Unable to clone https://github.com/actions/setup-nodejs refs/heads/v3: repository not found`
=> fix(examples): Updated 'setup-nodejs' actions to 'setup-node'

README.md
The README says to use `policy-pack` and `policy-pack-config`, but these aren't correct based on the implementation. They should be `policyPacks` and `policyPackConfig`.
Fixes #1024
=> Fix policy-related options in README.md

.github/codeql/codeql-config.yml, .github/workflows/codeql.yml
As a best practice for security, enable code scanning with CodeQL.
This was largely generated via clicking "enabling code scanning" with CodeQL through the GH website, but I did customize it by adding a configuration file so it would ignore the `dist` dir.
=> Enable code scanning with CodeQL

CHANGELOG.md, README.md, src/libs/libs/get-version.ts, src/libs/pulumi-cli.ts
Add a new "dev" option for the version field, that allows users to install the latest dev release automatically.
Fixes https://github.com/pulumi/actions/issues/1039
=> allow getting latest dev version

CHANGELOG.md
Prepare the changelog for the 4.6.0 release.  We already have a changelog entry for 4.6.0, but there was never an actual release for that, so let's re-use that, and include the other changes that have happened since.
=> prepare changelog for 4.6.0

CHANGELOG.md
The latest version should be a major version bump, since updating the nodejs version requires that.
=> update changelog to 5.0.0

CHANGELOG.md, src/libs/pulumi-cli.ts, src/login.ts, src/main.ts
Currently if the login fails as part of the GitHub action, we just silently ignore that.  This can be very confusing when steps further down the line fail, e.g. with "error: PULUMI_ACCESS_TOKEN must be set for login during non-interactive CLI sessions", even though the user has set the access token.
Instead of just continuing our merry way when the login fails, fail the action and let the user know.
This might be the cause of https://github.com/pulumi/actions/issues/1014.  The symptoms match, though it's unclear if there is anything else going on in that issue.
/cc @hisuwh
=> return error when login fails

src/__tests__/run.test.ts, src/libs/envs.ts
Follow up to https://github.com/pulumi/actions/pull/1062, since that seems to have broken the tests (they aren't being run on PR).  Also clean up the environment variable that we don't need anymore that I missed earlier.
=> fixup tests; clean up environment variables

README.md
We released v5 of the GitHub action, so we should update the readme to reflect that.  Also add a blurb about upgrading from v4 to v5.
=> update readme for v5

CHANGELOG.md, src/main.ts
Aparently `pulumi login` can fail, and yet other pulumi commands that follow can succeed (see https://github.com/pulumi/actions/issues/1081).
Instead of failing outright when login fails, just print a warning, so people are not confused when further errors happen later.
Fixes https://github.com/pulumi/actions/issues/1081
=> return a warning instead of an error on login failure

CHANGELOG.md, README.md, action.yml, package.json, src/__tests__/config.test.ts, src/config.ts
Adds support for --suppress-progress and --suppress-outputs parameters of stack up, preview, destroy and refresh.
Requires changes releasesd in the automation api (pulumi/pulumi 3.109 - https://github.com/pulumi/pulumi/pull/15596)
Original issue described here:
fixes #1108
=> Allow suppressing progress dots and outputs

.github/workflows/codeql.yml, README.md
Prepare this repo for switching its main branch name to `main` by making the workflows run on both `master` and `main`.  Some workflows already run that way, but make sure all of them do, ahead of going ahead and renaming it.
Once the branch is renamed, we can drop the build on `master` here.
=> prepare for renaming master to main

.github/workflows/codeql.yml, .github/workflows/test.yml, .github/workflows/update_dist.yml, .github/workflows/workflow.yml, CONTRIBUTING.md, README.md
We've renamed `master` to `main`.  Update the branch references from master to main, and remove the references to master in the github actions workflow files.
=> update references from master to main

.github/workflows/workflow.yml
We're using a very old version of Go here, which apparently can't be installed at least through the GitHub action anymore.  We're not supporting that version since a long time, and there really is no reason why we shouldn't use the latest version of Golang here, so do just that.
=> upgrade go used in workflows to latest

CHANGELOG.md, src/main.ts
We only allow the `comment-on-pr` option inside of pull requests. This makes sense because we wouldn't be able to comment on anything otherwise.  However with the `comment-on-pr-number` option gives us a PR number to comment on, so it can make sense with any type of GitHub actions event.  This used to work before #813, and it looks like disallowing this was accidental rather than intentional.
Make this work again.
Fixes #1177
=> make `comment-on-pr-number` option work even outside of pull-request events

README.md
Closes https://github.com/pulumi/actions/issues/934
This is already implemented here: 
https://github.com/pulumi/actions/blob/042fe5b09b30a1c9ca9c240a776a92f865df1723/src/libs/libs/get-version.ts#L47-L51
=> Document "latest" version specifier

CHANGELOG.md, README.md, action.yml, src/__tests__/run.test.ts, src/config.ts
Similar to how [Setup
Node](https://github.com/actions/setup-node/blob/main/docs/advanced-usage.md?rgh-link-date=2024-06-24T19%3A12%3A42Z#node-version-file) action works, this adds a new `pulumi-version-file` option that allows users to specify a file to read the version from.
A lot of our providers use the `.pulumi.version` file to store the current version of pulumi and we want to be able to use that version rather than relying on what is already installed.
re https://github.com/pulumi/ci-mgmt/pull/990
=> feat: add option `pulumi-version-file`

CHANGELOG.md, src/libs/pulumi-cli.ts
Version 3.120.0 of Pulumi contains a P0 that means `Delete` operations are largely broken. As a result, we'd really like to ensure it's used as little as possible. This commit adds 3.120.0 to the list of "known-bad" versions in the GitHub action, so that we'll force a download of a newer version in the event that 3.120.0 is the default available.
=> Add 3.120.0 to the list of known-bad versions

CHANGELOG.md, src/__tests__/config.test.ts, src/config.ts
The pulumi-version-file option was introduced in https://github.com/pulumi/actions/pull/1204.  However it was only introduced for installation mode, not if a pulumi command is given. The latter has separate config parsing code, so let's introduce the same option there as well.
Fixes: https://github.com/pulumi/actions/issues/1215
=> make pulumi-version-file also work in non-install mode

CHANGELOG.md, src/libs/pulumi-cli.ts
Users can pass 'latest' as the 'pulumi-version' configuration setting. This currently means that they always download the latest version of the CLI, regardless of whether that's already installed or not.
We can do better here and check if the latest version matches the one already installed on the runner, and in that case skip the download.
Fixes https://github.com/pulumi/actions/issues/1221
=> only install new pulumi version when there's a newer one available

CHANGELOG.md
Includes the bugfix for making the `pulumi-version-file` option work in non-install mode as well, and a fix for only downloading the latest version when it's actually necessary.
=> update changelog for 5.3.3

src/main.ts
`makeConfig` is not an async function, so the await here has no effect.  Remove it to clean this up.
This is not a necessary change at all, but I need to merge a change to test the config settings I've changed for re-enabling mandatory code reviews for this repo, while also not having the issues mentioned in https://github.com/pulumi/actions/issues/1148.
=> remove unnecessary await

.github/workflows/update_dist.yml
We can't make the default GitHub actions user bypass the branch checks.  However we can set up pulumi-bot to be able to do so.  Set GITHUB_TOKEN to PULUMI_BOT_TOKEN, to hopefully make the push from the pulumi-bot user.
=> set PULUMI_BOT_TOKEN when updating dist files

CHANGELOG.md, README.md, action.yml, src/__tests__/config.test.ts, src/config.ts, src/libs/__tests__/pr.test.ts, src/libs/pr.ts
I believe that the resources summary is the most important component of the output provided by pulumi preview and should always be included in the pull request comment. When trimming from the back, long outputs will not contain this information, which requires navigating to the checks tab and looking at the output there. 
Perhaps this is just a reflection of how I use pulumi but don't think so because we are all conditioned by the local use of the pulumi cli. When we run pulumi preview locally the output ends up right at the bottom so the first thing we see is the summary something like this:
```
Resources:
~ 85 to update
+-26 to replace
111 changes. 1062 unchanged
```
In many cases this is all the information that is needed to confirm that I'm ready to run pulumi up. Other times I need …
=> Trim PR comments from the front.

CHANGELOG.md, src/libs/pr.ts
Fixing small issue where the warning message would always be added to the commit message if `always-include-summary` was set to `true`. This fixes it so it only shows when the output is trimmed.
=> only log warning if output is actually trimmed

package.json
This includes https://github.com/pulumi/pulumi/pull/17209, which we need to fully support the changes made in https://github.com/pulumi/actions/pull/1118, and thus the 6.0.0 release of the pulumi action.
=> upgrade @pulumi/pulumi to 3.134.0

CHANGELOG.md
This includes a breaking change from https://github.com/pulumi/actions/pull/1118, so we should release a new major version.
=> prepare the changelog for the 6.0.0 release

.github/workflows/immutable-action.yml
We're switching over to publishing immutable actions from this repo. For this we need to make sure that immutable actions are published at each release of this repo.
With this, we can keep following our current release process, and whenever a new release is published, this action will create a new immutable actions package, that will then be available to users.
(This should only be merged after the current migration process (see https://github.com/pulumi/actions/actions/workflows/immutable-actions-migration/migrate_release) is completed, so that packages will always be in the right order.  Though it wouldn't be a big deal if they were out of order either.  Cosmetically it's nicer if they are in order though)
Fixes https://github.com/pulumi/home/issues/3695
=> add workflow for publishing immutable actions

CHANGELOG.md, src/main.ts
Users need to be able to know any diagnostics emitted by actions, so
this change adds some logging around stderr.
Fixes #1316
=> Log stderr from commands.

.github/workflows/test.yml, .github/workflows/workflow.yml, CHANGELOG.md, src/main.ts
This commit fixes the `output` command to work without having to have a workDir specified to a location with a Pulumi.yaml file. It does this by avoiding calls to `LocalWorkspace.createOrSelectStack`/`selectStack` when the command is `output`. This allows the `output` command to work with any stack, even when there is not a local project available.
Additionally, when the command is `output`, don't attempt to comment on the PR; only actual pulumi operations (like the `up` command) should do that.
Fixes #868
=> Fix the `output` command

CHANGELOG.md, src/libs/__tests__/pr.test.ts, src/libs/pr.ts
👋🏼 
I brought this up in my company's shared Slack with y'all. Seemed pretty low effort so I decided to forego the issue creation.
The idea is to offer a clickable link to the update run. Currently, since it is within the `<pre>` tags, the link is not clickable and must be highlighted in a window that is likely horizontally scrolling. The other alternative is to find the clickable link within the GitHub Action logs.
We've seen a few times where both the author and the reviewer have failed to double-check the preview run to ensure we're not causing any surprises. My hope is that by making it easier to double-check the preview output in Pulumi, that the likelihood of forgetting to check the output will decrease.
I could see an argument for putting the `View Live` link outside of the …
=> Add a clickable View Live link before pre-block

.github/workflows/update_dist.yml
These changes migrate this repo's GitHub Actions Workflows to use ESC secrets instead of GitHub Secrets.
The changes are largely mechanical:
- Common configuration for all ESC actions within a workflow is added to the workflow's environment variables
- Permissions are expanded as necessary for workflows that do not grant `id-token: write` permissions
- `read-all` permissions are replaced with the union of all explicit read permissions and `id-token: write`
- Default permissions are replaced with `write-all`, which is the equivalent of all explicit write permissions and
`id-token: write`
- Explicit permissions are modified to grant `id-token: write`
- A step that fetches ESC secrets and populates environment variables is added to each step that reads secrets
- Direct references to secrets …
=> Use ESC secrets

.github/test-stacks/dotnet/Program.cs, .github/test-stacks/golang/main.go, .github/test-stacks/nodejs/index.ts, .github/test-stacks/python/__main__.py, .github/workflows/test.yml, CHANGELOG.md, README.md, action.yml, src/__tests__/config.test.ts, src/config.ts, src/main.ts
Adding two optional inputs that are already [supported by @pulumi/automation](https://github.com/pulumi/pulumi/blob/master/sdk/nodejs/automation/stack.ts#L856-L868) 
fixes: https://github.com/pulumi/actions/issues/589
Unfortunately there's no functionality in @pulumi/automation supporting args passing.
=> feat: debug and verbosity

CHANGELOG.md, src/__tests__/config.test.ts, src/config.ts
The action code provides a user agent string to the automation api, for informational purposes.  Looks like the string is out of date; it still says "v5".  For example, some output from an unrelated issue:
```
stderr: Command failed with exit code 255: pulumi up --yes --skip-preview --diff --exec-agent pulumi/actions@v5 --color auto --exec-kind auto.local --stack dev-eus-00-wil-in1 --non-interactive
[resource plugin random-4.18.2] installing
[resource plugin random-4.18.1] installing
[resource plugin random-4.18.0] installing
[resource plugin azuread-6.4.0] installing
[resource plugin azure-native-3.2.0] installing
error: Status=400 Code="CertificateInUse" Message="Certificate 'cert-d5add54c6ad5054e50af24f769f45cf5' is used by existing custom domains."
```
=> update "user agent" string from `pulumi/actions@v5` to `pulumi/actions@v6`

.github/workflows/export-repo-secrets.yml, .github/workflows/update_dist.yml
This repository has repository-specific secrets that need to be migrated to ESC. These changes replace the usage of the common GHA ESC environment with the repository-specific environment.
=> Use repo-specific ESC environment
