pulumi/actions

README.md
examples/.github/workflows/pull_request.yml
examples/.github/workflows/push.yml

Part of https://github.com/pulumi/docs/issues/1533.

Update to use the new GitHub Actions syntax

---

examples/.github/workflows/push.yml

See the PR: https://github.com/pulumi/pulumi/pull/4477
Dockerfile: https://github.com/pulumi/pulumi/blob/249140242ebbe241b0869421f3700e75ae28402b/docker/actions/Dockerfile#L28-L29

chore: remove yes flag

---

entrypoint.sh

Fixes: https://github.com/pulumi/pulumi/issues/4327

Ensuring Pulumi login happens after GCP Service auth

---

README.md

Remove AWS env from GCP example

Remove AWS env from GCP example

---

CHANGELOG.md
README.md
src/__tests__/config.test.ts
src/config.ts
src/libs/__tests__/pr.test.ts
src/libs/pr.ts
src/main.ts

Resolves: https://github.com/pulumi/actions/issues/31 "Github Bot should edit previous comment instead of posting new one."

Edit previous PR comment instead of posting new one

---

.github/workflows/smoke_test_cli_version.yml
.github/workflows/workflow.yml
package.json
yarn.lock

Closes: #237
Closes: #236
Closes: #229
Closes: #226
Closes: #225

Summate the Dependabot package updates

---

src/libs/pulumi-cli.ts

Pulumi will install over the top of what is already there and we
will "upgrade" the existing version

No need to delete Pulumi homedirectory when installing CLI

---

package.json
yarn.lock

Closes: #269
Closes: #270
Closes: #271
Closes: #272
Closes: #273﻿

Merging dependabot PRs together June 10th

---

src/libs/__tests__/pr.test.ts
src/libs/pr.ts
src/main.ts

resolves https://github.com/pulumi/actions/issues/200 Improve Pull Request comments

Improve Pull Request comments

---

action.yml
package.json
src/libs/__tests__/pr.test.ts
src/libs/pr.ts
src/main.ts
yarn.lock

fix: pull request message authentication

---

CHANGELOG.md
src/libs/__tests__/get-platform.test.ts
src/libs/pulumi-cli.ts

Added support for the Pulumi GitHub Action on arm64 based architecture.

feat: Add support for arm64 architecture

---

src/main.ts

Hello. I caught what I believe to be a typo while scrolling through some Pulumi logs.

remove typo from debug logs

---

CHANGELOG.md
src/libs/__tests__/pr.test.ts
src/libs/pr.ts

fix: too long body throws

---

.github/workflows/update_dist.yml
.github/workflows/workflow.yml
CHANGELOG.md
action.yml

Unsure if this needs to be a breaking change, but probably smart?

chore: bump to node@16

---

README.md

This PR adds a description of the release cadence for this repository. I propose we cut a monthly release since the process takes < 5 minutes.
Closes https://github.com/pulumi/actions/issues/669

Add release schedule and description of cadence.

---

CHANGELOG.md
action.yml

Based on discussion in https://github.com/pulumi/actions/pull/651

Revert node16 upgrade

---

CHANGELOG.md

Let's cut v3.18.1 to address [this](https://github.com/pulumi/actions/issues/677) P1.

Update CHANGELOG with release notes.

---

CHANGELOG.md

In preparation for the v3.19.1 release, this PR updates the changelog.

Update changelog for v3.19.1

---

examples/dotnet-pulumi.yaml
examples/go-pulumi.yaml
examples/nodejs-aws.yaml
examples/nodejs-azure.yaml
examples/nodejs-google.yaml
examples/nodejs-local.yaml
examples/nodejs-pulumi.yaml
examples/python-pulumi.yaml

Updates dependencies and improves formatting

chore: update examples

---

CHANGELOG.md
package.json
src/libs/__mocks__/@actions/exec.ts
src/libs/__tests__/exec.test.ts
src/libs/__tests__/pr.test.ts
src/libs/exec.ts
src/login.ts
yarn.lock

No clue why tests are failing 🤷‍♂️
might fix #731

fix: no output issue

---

README.md

pairing this with https://github.com/pulumi/pulumi-hugo/pull/2054
super open to feedback if yall would prefer this included in a different way

clarify stack name

---

CHANGELOG.md

Update changelog for 3.20.0

---

examples/nodejs-google-workload-identity-federation.yaml

docs: Add example for Google Workflow Identity Federation

---

README.md

related to https://github.com/pulumi/actions/issues/752

chore: fix readme with the right node deprecation date

---

examples/nodejs-aws.yaml

Correct typo in action name.
Fixes https://github.com/pulumi/actions/issues/839

  Correct typo in action name.

---

CHANGELOG.md

This PR updates the changelog in preparation for the release of v3.21.0.

Cut release of v3.21.0

---

README.md
src/login.ts

Pulumi SaaS/Service should now be called Pulumi Cloud

Pulumi Service => Pulumi Cloud

---

src/__tests__/config.test.ts
src/config.ts

Just a tiny thing I noticed while working with the action.

fix user agent

---

CHANGELOG.md

For https://github.com/pulumi/actions/issues/1081.

update changelog for 5.1.1 release

---

README.md

Maybe this is what was suggested in https://github.com/pulumi/actions/issues/1075.  Either way it seems like a good thing to update.

Update to latest actions/checkout in README

---

package.json
yarn.lock

Fixes https://github.com/pulumi/actions/issues/1126 (hopefully)

Upgrade lint-changed

---

CHANGELOG.md

Update the changelog for a patch release including #1178.

update changelog for 5.2.4

---

CHANGELOG.md

Update the changelog for a minor release including #1204

update changelog for 5.3.0

---

CHANGELOG.md

update the changelog for a minor release including #1208

update changelog for 5.3.1

---

CHANGELOG.md

Release 5.5.0, including the external contribution from https://github.com/pulumi/actions/pull/1252.

Release 5.5.0 of the action

---

CHANGELOG.md

This includes a small bugfix for the feature introduced in the last release.

prepare for 5.5.1 release

---

CHANGELOG.md
src/__tests__/run.test.ts
src/login.ts
src/main.ts

Make `pulumi login` respect configuration in `Pulumi.yaml`

---

README.md
action.yml
package.json
src/__tests__/config.test.ts
src/config.ts
yarn.lock

Revert "feat: add run-program flag support"
